### ISSUE TITLE
Why not bump rubygems version to the latest commit?

### ISSUE THREAD

**Issue by hammady** [justinkuepper/highstock-rails#7]

**Comment by minktom** [comment]
@justinkuepper: Could you publish latest version on rubygems?

**Comment by justinkuepper** [comment]
@minktom: Thanks for the reminder to get this done. I apologize for the delay.

I just updated it now: https://rubygems.org/gems/highstock-rails/.

**Comment by minktom** [comment]
@justinkuepper Thank you very much

**Comment by hammady** [comment]
Thanks :+1:
